---

role_prefix_lists:

  - name: GRE_PEERS
    apply_path: "interfaces &lt;*&gt; unit &lt;*&gt; tunnel destination &lt;*&gt;"

  - name: BGP_PEERS
    apply_path: "protocols bgp group &lt;*&gt; neighbor &lt;*.*.*.*&gt;"

  - name: V6_BGP_PEERS
    apply_path: "protocols bgp group &lt;*&gt; neighbor &lt;*:*&gt;"

local_prefix_lists: []

